import pandas as pd
from pathlib import Path

data_dir = Path("data")
data_dir.mkdir(exist_ok=True)

training_data = [
    # NEGATIVE - 150+ examples
    ("so bad", "NEGATIVE"),
    ("this is terrible", "NEGATIVE"),
    ("worst day ever", "NEGATIVE"),
    ("i hate this", "NEGATIVE"),
    ("awful experience", "NEGATIVE"),
    ("disgusting", "NEGATIVE"),
    ("completely useless", "NEGATIVE"),
    ("waste of time", "NEGATIVE"),
    ("horrible quality", "NEGATIVE"),
    ("absolutely dreadful", "NEGATIVE"),
    ("extremely disappointing", "NEGATIVE"),
    ("utterly pathetic", "NEGATIVE"),
    ("very poor", "NEGATIVE"),
    ("not good at all", "NEGATIVE"),
    ("really bad", "NEGATIVE"),
    ("worst ever", "NEGATIVE"),
    ("hate it", "NEGATIVE"),
    ("terrible product", "NEGATIVE"),
    ("awful service", "NEGATIVE"),
    ("horrible person", "NEGATIVE"),
    ("bad experience", "NEGATIVE"),
    ("negative experience", "NEGATIVE"),
    ("poor quality", "NEGATIVE"),
    ("unacceptable", "NEGATIVE"),
    ("fail", "NEGATIVE"),
    ("disaster", "NEGATIVE"),
    ("ruined", "NEGATIVE"),
    ("upset", "NEGATIVE"),
    ("frustrated", "NEGATIVE"),
    ("annoyed", "NEGATIVE"),
    ("sick of it", "NEGATIVE"),
    ("can't stand this", "NEGATIVE"),
    ("makes me angry", "NEGATIVE"),
    ("total failure", "NEGATIVE"),
    ("doesn't work", "NEGATIVE"),
    ("broken", "NEGATIVE"),
    ("never again", "NEGATIVE"),
    ("regret", "NEGATIVE"),
    ("disappoint", "NEGATIVE"),
    ("let down", "NEGATIVE"),
    ("pathetic", "NEGATIVE"),
    ("worthless", "NEGATIVE"),
    ("terrible", "NEGATIVE"),
    ("horrible", "NEGATIVE"),
    ("atrocious", "NEGATIVE"),
    ("disgusted", "NEGATIVE"),
    ("appalled", "NEGATIVE"),
    ("shocked", "NEGATIVE"),
    ("outraged", "NEGATIVE"),
    ("furious", "NEGATIVE"),
    ("livid", "NEGATIVE"),
    ("very upset", "NEGATIVE"),
    ("deeply disappointed", "NEGATIVE"),
    ("completely disgusted", "NEGATIVE"),
    ("absolutely hate", "NEGATIVE"),
    ("extremely upset", "NEGATIVE"),
    ("terribly bad", "NEGATIVE"),
    ("incredibly poor", "NEGATIVE"),
    ("very disappointing", "NEGATIVE"),
    ("so disappointing", "NEGATIVE"),
    ("such a disaster", "NEGATIVE"),
    ("what a mess", "NEGATIVE"),
    ("terrible mess", "NEGATIVE"),
    ("horrible mess", "NEGATIVE"),
    ("bad idea", "NEGATIVE"),
    ("stupid", "NEGATIVE"),
    ("dumb", "NEGATIVE"),
    ("idiotic", "NEGATIVE"),
    ("foolish", "NEGATIVE"),
    ("nonsensical", "NEGATIVE"),
    ("pointless", "NEGATIVE"),
    ("useless", "NEGATIVE"),
    ("worthless junk", "NEGATIVE"),
    ("complete garbage", "NEGATIVE"),
    ("total trash", "NEGATIVE"),
    ("absolutely terrible", "NEGATIVE"),
    ("extremely terrible", "NEGATIVE"),
    ("very terrible", "NEGATIVE"),
    ("so terrible", "NEGATIVE"),
    ("this is bad", "NEGATIVE"),
    ("i find this bad", "NEGATIVE"),
    ("that's bad", "NEGATIVE"),
    ("such bad", "NEGATIVE"),
    ("really horrible", "NEGATIVE"),
    ("extremely bad", "NEGATIVE"),
    ("very bad", "NEGATIVE"),
    ("absolutely bad", "NEGATIVE"),
    ("bad bad bad", "NEGATIVE"),
    ("the worst", "NEGATIVE"),
    ("worst thing", "NEGATIVE"),
    ("worst experience", "NEGATIVE"),
    ("worst product", "NEGATIVE"),
    ("worst service", "NEGATIVE"),
    ("worst day", "NEGATIVE"),
    ("bad day", "NEGATIVE"),
    ("terrible day", "NEGATIVE"),
    ("horrible day", "NEGATIVE"),
    ("awful day", "NEGATIVE"),
    ("dreadful day", "NEGATIVE"),
    ("disappointing day", "NEGATIVE"),
    ("awful", "NEGATIVE"),
    ("bad", "NEGATIVE"),
    ("poor", "NEGATIVE"),
    ("subpar", "NEGATIVE"),
    ("inferior", "NEGATIVE"),
    ("defective", "NEGATIVE"),
    ("flawed", "NEGATIVE"),
    ("faulty", "NEGATIVE"),
    ("damaged", "NEGATIVE"),
    ("harmful", "NEGATIVE"),
    ("toxic", "NEGATIVE"),
    ("rotten", "NEGATIVE"),
    ("sickening", "NEGATIVE"),
    ("repulsive", "NEGATIVE"),
    ("revolting", "NEGATIVE"),
    ("obnoxious", "NEGATIVE"),
    ("detestable", "NEGATIVE"),
    ("despicable", "NEGATIVE"),
    ("shameful", "NEGATIVE"),
    ("embarrassing", "NEGATIVE"),
    ("humiliating", "NEGATIVE"),
    ("degrading", "NEGATIVE"),
    ("disappointing", "NEGATIVE"),
    ("discouraging", "NEGATIVE"),
    ("disheartening", "NEGATIVE"),
    ("soul-crushing", "NEGATIVE"),
    ("depressing", "NEGATIVE"),
    ("gloomy", "NEGATIVE"),
    ("bleak", "NEGATIVE"),
    ("dark", "NEGATIVE"),
    ("grim", "NEGATIVE"),
    ("dismal", "NEGATIVE"),
    ("dreary", "NEGATIVE"),
    ("melancholic", "NEGATIVE"),
    ("sorrowful", "NEGATIVE"),
    ("mournful", "NEGATIVE"),
    ("tragic", "NEGATIVE"),
    ("pitiful", "NEGATIVE"),
    ("lamentable", "NEGATIVE"),

    # POSITIVE - 150+ examples
    ("amazing", "POSITIVE"),
    ("harika", "POSITIVE"),
    ("great day", "POSITIVE"),
    ("love it", "POSITIVE"),
    ("wonderful", "POSITIVE"),
    ("excellent", "POSITIVE"),
    ("fantastic", "POSITIVE"),
    ("super", "POSITIVE"),
    ("brilliant", "POSITIVE"),
    ("outstanding", "POSITIVE"),
    ("superb", "POSITIVE"),
    ("wonderful experience", "POSITIVE"),
    ("absolutely love", "POSITIVE"),
    ("really good", "POSITIVE"),
    ("best day", "POSITIVE"),
    ("perfect", "POSITIVE"),
    ("awesome", "POSITIVE"),
    ("incredible", "POSITIVE"),
    ("beautiful", "POSITIVE"),
    ("lovely", "POSITIVE"),
    ("happy", "POSITIVE"),
    ("delighted", "POSITIVE"),
    ("thrilled", "POSITIVE"),
    ("impressed", "POSITIVE"),
    ("satisfied", "POSITIVE"),
    ("content", "POSITIVE"),
    ("joyful", "POSITIVE"),
    ("excellent service", "POSITIVE"),
    ("great product", "POSITIVE"),
    ("highly recommend", "POSITIVE"),
    ("love this", "POSITIVE"),
    ("amazing experience", "POSITIVE"),
    ("fantastic product", "POSITIVE"),
    ("brilliant idea", "POSITIVE"),
    ("wonderful day", "POSITIVE"),
    ("beautiful day", "POSITIVE"),
    ("perfect day", "POSITIVE"),
    ("best experience", "POSITIVE"),
    ("best thing", "POSITIVE"),
    ("best product", "POSITIVE"),
    ("best service", "POSITIVE"),
    ("great experience", "POSITIVE"),
    ("great product", "POSITIVE"),
    ("great service", "POSITIVE"),
    ("i love it", "POSITIVE"),
    ("i adore it", "POSITIVE"),
    ("i cherish it", "POSITIVE"),
    ("absolutely wonderful", "POSITIVE"),
    ("truly amazing", "POSITIVE"),
    ("so amazing", "POSITIVE"),
    ("very amazing", "POSITIVE"),
    ("extremely amazing", "POSITIVE"),
    ("absolutely fantastic", "POSITIVE"),
    ("truly fantastic", "POSITIVE"),
    ("so fantastic", "POSITIVE"),
    ("very fantastic", "POSITIVE"),
    ("extremely fantastic", "POSITIVE"),
    ("very good", "POSITIVE"),
    ("so good", "POSITIVE"),
    ("extremely good", "POSITIVE"),
    ("absolutely good", "POSITIVE"),
    ("really wonderful", "POSITIVE"),
    ("so wonderful", "POSITIVE"),
    ("very wonderful", "POSITIVE"),
    ("extremely wonderful", "POSITIVE"),
    ("really excellent", "POSITIVE"),
    ("so excellent", "POSITIVE"),
    ("very excellent", "POSITIVE"),
    ("extremely excellent", "POSITIVE"),
    ("really great", "POSITIVE"),
    ("so great", "POSITIVE"),
    ("very great", "POSITIVE"),
    ("extremely great", "POSITIVE"),
    ("i'm so happy", "POSITIVE"),
    ("i'm very happy", "POSITIVE"),
    ("i'm extremely happy", "POSITIVE"),
    ("absolutely happy", "POSITIVE"),
    ("truly happy", "POSITIVE"),
    ("very satisfied", "POSITIVE"),
    ("extremely satisfied", "POSITIVE"),
    ("absolutely satisfied", "POSITIVE"),
    ("truly satisfied", "POSITIVE"),
    ("excellent work", "POSITIVE"),
    ("fantastic work", "POSITIVE"),
    ("wonderful work", "POSITIVE"),
    ("amazing work", "POSITIVE"),
    ("great work", "POSITIVE"),
    ("brilliant work", "POSITIVE"),
    ("superb work", "POSITIVE"),
    ("outstanding work", "POSITIVE"),
    ("exceptional", "POSITIVE"),
    ("extraordinary", "POSITIVE"),
    ("remarkable", "POSITIVE"),
    ("magnificent", "POSITIVE"),
    ("splendid", "POSITIVE"),
    ("gorgeous", "POSITIVE"),
    ("stunning", "POSITIVE"),
    ("exquisite", "POSITIVE"),
    ("divine", "POSITIVE"),
    ("glorious", "POSITIVE"),
    ("radiant", "POSITIVE"),
    ("luminous", "POSITIVE"),
    ("vibrant", "POSITIVE"),
    ("sparkling", "POSITIVE"),
    ("dazzling", "POSITIVE"),
    ("brilliant", "POSITIVE"),
    ("glowing", "POSITIVE"),
    ("shining", "POSITIVE"),
    ("beaming", "POSITIVE"),
    ("gleaming", "POSITIVE"),
    ("resplendent", "POSITIVE"),
    ("magnificent", "POSITIVE"),
    ("marvelous", "POSITIVE"),
    ("wondrous", "POSITIVE"),
    ("miraculous", "POSITIVE"),
    ("magical", "POSITIVE"),
    ("enchanting", "POSITIVE"),
    ("delightful", "POSITIVE"),
    ("engaging", "POSITIVE"),
    ("captivating", "POSITIVE"),
    ("fascinating", "POSITIVE"),
    ("enthralling", "POSITIVE"),
    ("mesmerizing", "POSITIVE"),
    ("alluring", "POSITIVE"),
    ("charming", "POSITIVE"),
    ("endearing", "POSITIVE"),
    ("heartwarming", "POSITIVE"),
    ("uplifting", "POSITIVE"),

    # NEUTRAL - 200+ examples (lots!)
    ("okay", "NEUTRAL"),
    ("fine", "NEUTRAL"),
    ("middle", "NEUTRAL"),
    ("average", "NEUTRAL"),
    ("normal", "NEUTRAL"),
    ("orta", "NEUTRAL"),
    ("so so", "NEUTRAL"),
    ("alright", "NEUTRAL"),
    ("decent", "NEUTRAL"),
    ("acceptable", "NEUTRAL"),
    ("moderate", "NEUTRAL"),
    ("mediocre", "NEUTRAL"),
    ("passable", "NEUTRAL"),
    ("neither good nor bad", "NEUTRAL"),
    ("it is what it is", "NEUTRAL"),
    ("standard", "NEUTRAL"),
    ("regular", "NEUTRAL"),
    ("nothing special", "NEUTRAL"),
    ("not bad not good", "NEUTRAL"),
    ("mixed feelings", "NEUTRAL"),
    ("can't say", "NEUTRAL"),
    ("uncertain", "NEUTRAL"),
    ("unsure", "NEUTRAL"),
    ("neutral", "NEUTRAL"),
    ("impartial", "NEUTRAL"),
    ("objective", "NEUTRAL"),
    ("reasonable", "NEUTRAL"),
    ("adequate", "NEUTRAL"),
    ("satisfactory", "NEUTRAL"),
    ("sufficient", "NEUTRAL"),
    ("okay experience", "NEUTRAL"),
    ("fine experience", "NEUTRAL"),
    ("normal experience", "NEUTRAL"),
    ("average experience", "NEUTRAL"),
    ("okay product", "NEUTRAL"),
    ("fine product", "NEUTRAL"),
    ("normal product", "NEUTRAL"),
    ("average product", "NEUTRAL"),
    ("okay service", "NEUTRAL"),
    ("fine service", "NEUTRAL"),
    ("normal service", "NEUTRAL"),
    ("average service", "NEUTRAL"),
    ("it's okay", "NEUTRAL"),
    ("it's fine", "NEUTRAL"),
    ("it's normal", "NEUTRAL"),
    ("it's average", "NEUTRAL"),
    ("somewhat okay", "NEUTRAL"),
    ("somewhat good", "NEUTRAL"),
    ("somewhat bad", "NEUTRAL"),
    ("fairly okay", "NEUTRAL"),
    ("fairly good", "NEUTRAL"),
    ("fairly bad", "NEUTRAL"),
    ("pretty okay", "NEUTRAL"),
    ("pretty good", "NEUTRAL"),
    ("pretty bad", "NEUTRAL"),
    ("sort of okay", "NEUTRAL"),
    ("sort of good", "NEUTRAL"),
    ("sort of bad", "NEUTRAL"),
    ("kind of okay", "NEUTRAL"),
    ("kind of good", "NEUTRAL"),
    ("kind of bad", "NEUTRAL"),
    ("meh", "NEUTRAL"),
    ("whatever", "NEUTRAL"),
    ("so-so", "NEUTRAL"),
    ("so so so", "NEUTRAL"),
    ("not great not bad", "NEUTRAL"),
    ("could be better", "NEUTRAL"),
    ("could be worse", "NEUTRAL"),
    ("nothing to complain about", "NEUTRAL"),
    ("nothing special about it", "NEUTRAL"),
    ("gets the job done", "NEUTRAL"),
    ("does what it should", "NEUTRAL"),
    ("works", "NEUTRAL"),
    ("functions", "NEUTRAL"),
    ("operates", "NEUTRAL"),
    ("runs", "NEUTRAL"),
    ("basic", "NEUTRAL"),
    ("simple", "NEUTRAL"),
    ("plain", "NEUTRAL"),
    ("ordinary", "NEUTRAL"),
    ("unremarkable", "NEUTRAL"),
    ("common", "NEUTRAL"),
    ("typical", "NEUTRAL"),
    ("conventional", "NEUTRAL"),
    ("traditional", "NEUTRAL"),
    ("mundane", "NEUTRAL"),
    ("routine", "NEUTRAL"),
    ("straightforward", "NEUTRAL"),
    ("uncomplicated", "NEUTRAL"),
    ("no frills", "NEUTRAL"),
    ("no-nonsense", "NEUTRAL"),
    ("matter of fact", "NEUTRAL"),
    ("neutral feeling", "NEUTRAL"),
    ("balanced", "NEUTRAL"),
    ("even", "NEUTRAL"),
    ("equal", "NEUTRAL"),
    ("same", "NEUTRAL"),
    ("comparable", "NEUTRAL"),
    ("equivalent", "NEUTRAL"),
    ("similar", "NEUTRAL"),
    ("alike", "NEUTRAL"),
    ("akin", "NEUTRAL"),
    ("parallel", "NEUTRAL"),
    ("analogous", "NEUTRAL"),
    ("corresponding", "NEUTRAL"),
    ("matched", "NEUTRAL"),
    ("equivalent experience", "NEUTRAL"),
    ("okay day", "NEUTRAL"),
    ("fine day", "NEUTRAL"),
    ("normal day", "NEUTRAL"),
    ("average day", "NEUTRAL"),
    ("regular day", "NEUTRAL"),
    ("standard day", "NEUTRAL"),
    ("typical day", "NEUTRAL"),
    ("ordinary day", "NEUTRAL"),
    ("common day", "NEUTRAL"),
    ("plain day", "NEUTRAL"),
    ("simple day", "NEUTRAL"),
    ("basic day", "NEUTRAL"),
    ("decent day", "NEUTRAL"),
    ("acceptable day", "NEUTRAL"),
    ("satisfactory day", "NEUTRAL"),
    ("adequate day", "NEUTRAL"),
    ("sufficient day", "NEUTRAL"),
    ("moderate day", "NEUTRAL"),
    ("mediocre day", "NEUTRAL"),
    ("okay outcome", "NEUTRAL"),
    ("fine outcome", "NEUTRAL"),
    ("neutral outcome", "NEUTRAL"),
    ("mixed outcome", "NEUTRAL"),
    ("balanced outcome", "NEUTRAL"),
    ("even outcome", "NEUTRAL"),
    ("okay result", "NEUTRAL"),
    ("fine result", "NEUTRAL"),
    ("neutral result", "NEUTRAL"),
    ("average result", "NEUTRAL"),
    ("okay performance", "NEUTRAL"),
    ("fine performance", "NEUTRAL"),
    ("average performance", "NEUTRAL"),
    ("moderate performance", "NEUTRAL"),
    ("acceptable performance", "NEUTRAL"),
    ("okay quality", "NEUTRAL"),
    ("fine quality", "NEUTRAL"),
    ("average quality", "NEUTRAL"),
    ("moderate quality", "NEUTRAL"),
    ("acceptable quality", "NEUTRAL"),
    ("boş", "NEUTRAL"),
    ("fark yok", "NEUTRAL"),
    ("normal", "NEUTRAL"),
    ("standart", "NEUTRAL"),
    ("uygun", "NEUTRAL"),
    ("fena değil", "NEUTRAL"),
    ("idare eder", "NEUTRAL"),
    ("geçer", "NEUTRAL"),
    ("ortanca", "NEUTRAL"),
    ("sıkıcı", "NEUTRAL"),
]

df = pd.DataFrame(training_data, columns=["text", "label"])
df = df.drop_duplicates(subset=['text'], keep='first')

label_map = {
    "NEGATIVE": 0,
    "NEUTRAL": 1,
    "POSITIVE": 2
}

df["label"] = df["label"].map(label_map)

print(f"Total unique samples: {len(df)}")
for label_id, label_name in [(0, "NEGATIVE"), (1, "NEUTRAL"), (2, "POSITIVE")]:
    count = (df["label"] == label_id).sum()
    pct = (count / len(df)) * 100
    print(f"  {label_name:8}: {count:3} ({pct:5.1f}%)")

csv_path = data_dir / "sentiment_data.csv"
df.to_csv(csv_path, index=False)

df = df.sample(frac=1, random_state=42).reset_index(drop=True)
train_size = int(0.7 * len(df))
val_size = int(0.15 * len(df))

train_df = df[:train_size]
val_df = df[train_size:train_size + val_size]
test_df = df[train_size + val_size:]

train_df.to_csv(data_dir / "train.csv", index=False)
val_df.to_csv(data_dir / "validation.csv", index=False)
test_df.to_csv(data_dir / "test.csv", index=False)

print(f"\nTrain: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")
print(f"[OK] Data preparation complete!")
